rongpu@cori08:temp> srun -N 1 -C haswell -c 64 -t 04:00:00 -q interactive python find_corrupted_blobmask.py 
105664 exposures
22000 / 105664
23000 / 105664
577943 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2a/CP20160926/c4d_160927_091257_ooi_z_ls9-blobmask.npz
52000 / 105664
78000 / 105664
79000 / 105664
105000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaaabc976a0>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
10000 / 105664
11000 / 105664
27000 / 105664
28000 / 105664
53000 / 105664
54000 / 105664
80000 / 105664
7000 / 105664
8000 / 105664
30000 / 105664
31000 / 105664
55000 / 105664
56000 / 105664
81000 / 105664
82000 / 105664
12000 / 105664
13000 / 105664
29000 / 105664
57000 / 105664
83000 / 105664
84000 / 105664
5000 / 105664
6000 / 105664
32000 / 105664
33000 / 105664
62000 / 105664
85000 / 105664
349335 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2a/CP20140817/c4d_140818_063938_ooi_z_ls9-blobmask.npz
14000 / 105664
43000 / 105664
44000 / 105664
605581 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2/CP20161230/c4d_161231_014834_ooi_r_ls9-blobmask.npz
60000 / 105664
61000 / 105664
86000 / 105664
87000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaaad5beba8>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaabae95550>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
24000 / 105664
38000 / 105664
39000 / 105664
73000 / 105664
74000 / 105664
103000 / 105664
104000 / 105664
25000 / 105664
26000 / 105664
45000 / 105664
46000 / 105664
58000 / 105664
59000 / 105664
88000 / 105664
89000 / 105664
9000 / 105664
34000 / 105664
63000 / 105664
64000 / 105664
90000 / 105664
17000 / 105664
18000 / 105664
47000 / 105664
67000 / 105664
93000 / 105664
94000 / 105664
4000 / 105664
35000 / 105664
36000 / 105664
65000 / 105664
66000 / 105664
91000 / 105664
92000 / 105664
15000 / 105664
16000 / 105664
50000 / 105664
51000 / 105664
76000 / 105664
77000 / 105664
691514 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.1/CP20171027/c4d_171028_012841_ooi_z_v1-blobmask.npz
784973 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.1/CP20181018/c4d_181019_022956_ooi_z_v1-blobmask.npz
100000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaaba8a5940>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aab4a19df98>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
20000 / 105664
21000 / 105664
40000 / 105664
41000 / 105664
68000 / 105664
69000 / 105664
95000 / 105664
2000 / 105664
3000 / 105664
242836 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2a/CP20131010/c4d_131011_073337_ooi_g_ls9-blobmask.npz
37000 / 105664
75000 / 105664
101000 / 105664
102000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaaad5beba8>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
0 / 105664
1000 / 105664
42000 / 105664
70000 / 105664
674014 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2a/CP20170831/c4d_170901_065640_ooi_z_ls9-blobmask.npz
98000 / 105664
99000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaaabc6a0b8>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
19000 / 105664
48000 / 105664
49000 / 105664
71000 / 105664
72000 / 105664
96000 / 105664
775108 /global/cfs/cdirs/desi/users/rongpu/dr9/decam_ccd_blob_mask/blob_mask/decam/CP/V4.8.2a/CP20180917/c4d_180918_050826_ooi_z_ls9-blobmask.npz
97000 / 105664
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x2aaabae959b0>>
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
Done!!!!!!!!!!!!!!!!!!!!!
rongpu@cori08:temp> 
